name: Keep PDF Unlocker Pro Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:        # Allow manual runs when needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping homepage
        run: |
          curl -L -s -o /dev/null -w "%{http_code}" https://pdf-unlocker-pro.onrender.com/
          echo "Pinged PDF Unlocker Pro homepage at $(date)"
      
      - name: Short delay
        run: sleep 15
      
      - name: Ping second page with user agent
        run: |
          curl -L -s -o /dev/null -w "%{http_code}" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
          https://pdf-unlocker-pro.onrender.com/
          echo "Sent second ping with browser user agent at $(date)"
      
      - name: Medium delay
        run: sleep 20
          
      - name: Final ping with different path
        run: |
          curl -L -s -o /dev/null -w "%{http_code}" \
          -H "Referer: https://www.google.com/" \
          -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" \
          https://pdf-unlocker-pro.onrender.com/faq
          echo "Completed final ping to FAQ page at $(date)" 